version: '3.8'

services:
  zonos:
    image: stanchino/zonos:20250409-0f52b38
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GRADIO_SHARE=False
      - GRADIO_SERVER_PORT=7860
    deploy:
      replicas: 1